AnadoluRentalWeb/AnadoluRentalWeb/Controllers/AracController.cs
using AnadoluRental.CrossCutting.Concretes.Helper;
using AnadoluRental.CrossCutting.Concretes.Logger;
using AnadoluRental.Models.Models;
using AnadoluRentalWeb.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AnadoluRentalWeb.Controllers
{
    public class AracController : Controller
    {
        string Baseurl = "http://localhost:54361/";

        // GET: Arac
        public async Task<ActionResult> Index()
        {

            Kullanici gelenK = (Kullanici)Session["kull"];

            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                    IList<Arac> aracListesi = null;
                    using (var result = await client.GetAsync("api/Arac"))
                    {
                        if (result.IsSuccessStatusCode)
                        {
                            var value = result.Content.ReadAsStringAsync().Result;

                            if (gelenK != null && (gelenK.kullRolID == 2 || gelenK.kullRolID == 3) && gelenK.kullSirketID > 0) // Yönetici veya Çalışan ise..
                            {
                                aracListesi = JsonConvert.DeserializeObject<ResponseContent<Arac>>(value).Data.Where(arac => (arac.aitOlduguSirketID == gelenK.kullSirketID)).ToList();
                            }
                            else
                            {
                                aracListesi = JsonConvert.DeserializeObject<ResponseContent<Arac>>(value).Data.ToList();
                            }
                        }
                    }
                    return View(aracListesi);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Hata Oluştu" + ex.Message);
            }
        }

        // GET: Arac/Goruntule/5
        public ActionResult Goruntule(int id)
        {
            if (Session["kull"] == null)
                return RedirectToAction("Index", "Home");

            return View(id);
        }

        // GET: Arac/YeniOlustur
        public async Task<ActionResult> YeniOlustur()
        {
            if (Session["kull"] == null)
                return RedirectToAction("Index", "Home");

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                IList<Sirket> sirketListesi = null;
                using (var result = await client.GetAsync("api/Sirket"))
                {
                    if (result.IsSuccessStatusCode)
                    {
                        var value = result.Content.ReadAsStringAsync().Result;

                        sirketListesi = JsonConvert.DeserializeObject<ResponseContent<Sirket>>(value).Data.ToList();
                    }
                }
                ViewBag.sirketListesi = sirketListesi;
            }
            return View();
        }

        // POST: Arac/YeniOlustur
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> YeniOlustur(FormCollection collection, HttpPostedFileBase uploadFile)
        {
            if (Session["kull"] == null)
                return RedirectToAction("Index", "Home");

            if (!ModelState.IsValid)
            {
                return RedirectToAction("YeniOlustur");
            }
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));

                    Arac yeniArac = new Arac();
                    yeniArac.aracMarka = collection["aracMarka"];
                    yeniArac.aracModel = collection["aracModel"];
                    yeniArac.gerekenEhliyetYasi = int.Parse(collection["gerekenEhliyetYasi"]);
                    yeniArac.minYasSiniri = int.Parse(collection["minYasSiniri"]);
                    yeniArac.gunlukSinirKM = int.Parse(collection["gunlukSinirKM"]);
                    yeniArac.aracKM = int.Parse(collection["aracKM"]);
                    yeniArac.airBagSayisi = int.Parse(collection["airBagSayisi"]);
                    yeniArac.bagacHacmi = int.Parse(collection["bagacHacmi"]);
                    yeniArac.koltukSayisi = int.Parse(collection["koltukSayisi"]);
                    yeniArac.gunlukKiralikFiyati = int.Parse(collection["gunlukKiralikFiyati"]);
                    if(collection["secilenSirket"]==null)
                        yeniArac.aitOlduguSirketID = int.Parse(collection["gelenK.kullSirketID"]);
                    else
                        yeniArac.aitOlduguSirketID = int.Parse(collection["secilenSirket"]);
                    //resim
                    if (uploadFile == null)
                    {
                        yeniArac.aracResim = "Content/img/arac/image_not_found.jpg";
                    }
                    else
                    {
                        string path = Path.Combine(Server.MapPath("~/Content/img/arac"), Path.GetFileName(yeniArac.aracID + "_" + uploadFile.FileName));
                        string kayitYeri = "Content/img/arac/" + yeniArac.aracID + "_" + uploadFile.FileName;

                        string silEski = Server.MapPath("~/" + yeniArac.aracResim);
                        if (System.IO.File.Exists(silEski))
                        {
                            System.IO.File.Delete(silEski);
                        }

                        yeniArac.aracResim = kayitYeri;
                        uploadFile.SaveAs(path);
                    }

                    var serializedProduct = JsonConvert.SerializeObject(yeniArac);
                    var content = new StringContent(serializedProduct, Encoding.UTF8, "application/json");
                    var result = await client.PostAsync("api/Arac", content);
                    if (result.IsSuccessStatusCode)
                        return RedirectToAction("Index");
                    return RedirectToAction("YeniOlustur");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                return RedirectToAction("YeniOlustur");
            }
        }

        // GET: Arac/Duzenle/41
        public async Task<ActionResult> Duzenle(int id)
        {
            if (Session["kull"] == null)
                return RedirectToAction("Index", "Home");

            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));

                    IList<Sirket> sirketListesi = null;
                    using (var result = await client.GetAsync("api/Sirket"))
                    {
                        if (result.IsSuccessStatusCode)
                        {
                            var value = result.Content.ReadAsStringAsync().Result;

                            sirketListesi = JsonConvert.DeserializeObject<ResponseContent<Sirket>>(value).Data.ToList();
                        }
                    }
                    ViewBag.sirketList = sirketListesi;

                    Arac arac = null;

                    using (var result = await client.GetAsync("api/Arac/" + id))
                    {
                        if (result.IsSuccessStatusCode)
                        {
                            var value = result.Content.ReadAsStringAsync().Result;

                            arac = JsonConvert.DeserializeObject<ResponseContent<Arac>>(value).Data.ToList().First();

                            return View(arac);
                        }
                    }

                    
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Hata Oluştu", ex);
            }
        }

        // POST: Arac/Duzenle/41
        [HttpPost]
        public async Task<ActionResult> Duzenle(int id, FormCollection collection, HttpPostedFileBase uploadFile)
        {
            if (Session["kull"] == null)
                return RedirectToAction("Index", "Home");

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(Baseurl);
                    client.DefaultRequestHeaders.Accept.Clear();
                    client.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));

                    Arac secilenArac = null;

                    using (var gelenArac = await client.GetAsync("api/Arac/" + id))

AnadoluRentalWeb/AnadoluRentalWeb/Views/Shared/_Layout.cshtml
@using AnadoluRental.Models.Models;
@{
    int gelenKullRolID = 0;
    Kullanici gelenK = (Kullanici)Session["kull"];
    if (gelenK == null)
    {
        gelenKullRolID = 0;
    }
    else
    {
        gelenKullRolID = (int)gelenK.kullRolID;
    }

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AnadoluRental</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AnadoluRental", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (gelenK != null) // Giriş Yapıldıysa
                    {
                        if (gelenK.kullRolID == 1) //Admin ise..
                        {
                            <li>@Html.ActionLink("Tüm Araçlar", "Index", "Arac")</li>
                            <li>@Html.ActionLink("Tüm Kiralananlar", "Index", "Kiralik")</li>
                            <li>@Html.ActionLink("Tüm Kullanıcılar", "Index", "Musteri")</li>
                            <li>@Html.ActionLink("Tüm Şirketler", "Index", "Sirket")</li>
                        }
                        else if (gelenK.kullRolID == 2) //Yönetici ise..
                        {
                            <li>@Html.ActionLink("Şirketin Araçları", "Index", "Arac")</li>
                            <li>@Html.ActionLink("Kiralanmış Araçlar", "Index", "Kiralik")</li>
                            <li>@Html.ActionLink("Personeller", "Index", "Musteri")</li>
                            <li>@Html.ActionLink("Şirket Bilgisi", "Duzenle", "Sirket", new { id = gelenK.kullSirketID }, new { @class = "" })</li>
                        }
                        else if (gelenK.kullRolID == 3) //Çalışan ise..
                        {
                            <li>@Html.ActionLink("Şirketin Araçları", "Index", "Arac")</li>
                            <li>@Html.ActionLink("Kiralanmış Araçlar", "Index", "Kiralik")</li>
                            <li>@Html.ActionLink("Müşteriler", "Index", "Musteri")</li>
                        }
                        else if (gelenK.kullRolID == 4) // Müşteri ise..
                        {
                            <li>@Html.ActionLink("Araçları Görüntüle", "Index", "Arac")</li>
                            <li>@Html.ActionLink("Tarihçe", "Index", "Home")</li>
                            <li>@Html.ActionLink("Vizyonumuz", "Index", "Home")</li>
                            <li>@Html.ActionLink("Bize Ulaşın", "Index", "Home")</li>
                        }

                    }
                    else // Giriş yapılmadıysa
                    {
                        <li>@Html.ActionLink("Tarihçe", "Index", "Home")</li>
                        <li>@Html.ActionLink("Vizyonumuz", "Index", "Home")</li>
                        <li>@Html.ActionLink("Bize Ulaşın", "Index", "Home")</li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (gelenKullRolID == 0)
                    {
                        <li>@Html.ActionLink("Kayıt Ol", "KayitOl", "Login")</li>
                        <li>@Html.ActionLink("Giriş Yap", "Index", "Login")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Hoşgeldiniz, " + @gelenK.Ad + " " + @gelenK.Soyad, "")</li>
                        <li> @Html.ActionLink("Profilim", "Index", "Profil") </li>
                        <li> @Html.ActionLink("Çıkış", "Logout", "Login") </li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content centre" style="width:1440px">
            @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AnadoluRental</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <style>
    div.centre {
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
</style>
</body>
</html>